// /challenges/ — every چالش on the site, newest first, on one page.
//
// WHY A PAGE. A چالش is an ordinary post whose body is a question, filed into
// whichever folder it belongs to (insight/, chairside/ …), so until now the
// only ways to find one were the section it happened to land in or a link to
// the newest one — a dead end the day after it is read. The premium tab's
// «پاسخ به چالش‌ها» card needed a real destination, and «the newest challenge»
// is not one (founder, 1405/06/30: a landing page, and the card leads there).
//
// NOTHING IS STORED AND NOTHING IS COMPUTED TWICE. Two files that already
// exist are joined at render time: plus/challenges.json (the PUBLIC half of
// every challenge — question + image — generated by tools/build_challenge_index.mjs
// on publish; the answer and the key points are never in any published file)
// and up-board/index.json (id/title/type/url/date for every page, written by
// tools/build_upboard_index.py on every publish). The catalog's own order is
// newest-first, so the list is too.
//
// THE READER'S OWN STATE comes from the one question the API already answers,
// GET /challenge?content_id= — sessionless, and for a signed-in reader it
// carries their attempt. A card whose reader has answered says so; nobody
// else's attempts are visible anywhere (RULE 6: released by one fact, the
// reader's own attempt row). Answering is premium and gated ON the challenge
// page itself (challenge.js) — this page only lists, and says once, at the
// end, who may answer.
import { el } from './util.js?v=152';
import { api, currentUser, meStatus } from './api.js?v=152';
import { pricingHref } from './premium-cta.js?v=152';

/** Which gate sent a buyer, for the pricing page's ?from= report. */
const FROM = 'gate-challenges';

// Carried onto the data fetches so one asset_version bump invalidates the code
// and the catalogs together — the same trick desboard-page.js plays.
const ASSET_V = '1';

async function loadData() {
  const [challenges, index] = await Promise.all([
    fetch('/plus/challenges.json?v=' + ASSET_V, { credentials: 'omit', cache: 'no-cache' })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error('challenges ' + r.status)))),
    fetch('/up-board/index.json?v=' + ASSET_V, { credentials: 'omit', cache: 'no-cache' })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error('index ' + r.status)))),
  ]);
  const by = (challenges && challenges.byContent) || {};
  const items = [];
  (index.items || []).forEach((m) => {
    const c = by[m.id];
    if (!c || !c.question) return;
    items.push({ cid: m.id, url: m.u, title: m.ti, sec: m.tf, date: m.d, question: c.question, image: c.image || '' });
  });
  return items;
}

/* -------------------------------------------------------------- render --- */

function card(it) {
  const media = it.image
    ? el('a', { class: 'ch-media', href: it.url, 'aria-hidden': 'true', tabindex: '-1' }, [
      el('img', { src: it.image, alt: '', loading: 'lazy', decoding: 'async' }),
    ])
    : null;
  return el('li', { class: 'ch-card', 'data-cid': it.cid }, [
    media,
    el('div', { class: 'ch-main' }, [
      el('p', { class: 'ch-meta' }, [
        el('span', { class: 'ch-sec' }, it.sec || ''),
        it.date ? el('span', { class: 'ch-date' }, it.date) : null,
        el('span', { class: 'ch-state', hidden: '' }),
      ].filter(Boolean)),
      el('a', { class: 'ch-title', href: it.url }, it.title || it.cid),
      el('p', { class: 'ch-q' }, it.question),
      el('a', { class: 'ch-go', href: it.url }, 'دیدن و پاسخ ›'),
    ]),
  ].filter(Boolean));
}

/**
 * The one line about who may answer, after the list. Three answers from /me
 * and each gets a different sentence: signed out (sign-in leads, the purchase
 * link follows — they may be a subscriber logged out on this device), free
 * (the premium line), premium (nothing — the list is theirs), and «could not
 * ask» (nothing — never an upsell for a redeploy).
 */
function whoMayAnswer(me) {
  if (me && me.tier === 'premium') return null;
  if (!me && meStatus() === 'error') return null;
  const buy = el('a', { href: pricingHref(FROM) }, 'اشتراک پریمیوم');
  if (!me) {
    return el('p', { class: 'ch-note' }, [
      'خواندن چالش‌ها برای همه آزاد است؛ پاسخ دادن ویژه‌ی ', buy, ' است. اگر اشتراک دارید، وارد شوید.',
    ]);
  }
  return el('p', { class: 'ch-note' }, ['خواندن چالش‌ها آزاد است؛ پاسخ دادن ویژه‌ی ', buy, ' است.']);
}

/** For a signed-in reader: mark the challenges they have already answered. */
function markAnswered(root, items) {
  items.forEach((it) => {
    api.challengeState(it.cid)
      .then((st) => {
        if (!st || !st.exists) return;
        // An attempt row is the one fact: `status` (queued/settled) or the
        // reader's own answer text is only ever present when one exists.
        const answered = !!(st.status || st.answer_text);
        if (!answered) return;
        root.querySelectorAll('[data-cid="' + it.cid + '"] .ch-state').forEach((n) => {
          n.textContent = 'پاسخ داده‌اید';
          n.hidden = false;
        });
      })
      .catch(() => { /* the list stands without the mark */ });
  });
}

export async function initChallengesPage(root) {
  if (!root) return;
  const list = el('ul', { class: 'ch-list' });
  const sub = document.getElementById('chSub');
  let items = [];
  try {
    items = await loadData();
  } catch (_) {
    root.appendChild(el('p', { class: 'ch-empty' }, 'فهرست چالش‌ها در دسترس نیست. کمی بعد دوباره تلاش کنید.'));
    return;
  }
  if (!items.length) {
    root.appendChild(el('p', { class: 'ch-empty' }, 'هنوز چالشی منتشر نشده است.'));
    return;
  }
  items.forEach((it) => list.appendChild(card(it)));
  root.appendChild(list);
  if (sub) sub.textContent = items.length === 1 ? 'یک چالش' : (new Intl.NumberFormat('fa-IR').format(items.length) + ' چالش');

  let me = null;
  try { me = await currentUser(); } catch (_) { me = null; }
  const note = whoMayAnswer(me);
  if (note) root.appendChild(note);
  if (me) markAnswered(root, items);
}
