/**
 * The gift-card flow stops collecting the code.
 *
 * 0021 assumed the buyer would paste their gift-card code into our form. That
 * works, but it means a bearer instrument — anyone holding the code can spend it
 * — travels through our page, our API and our database, and sits there until
 * somebody redeems it. The safer arrangement costs nothing: Amazon (and Apple)
 * will email a digital gift card straight to a recipient we name, so the code
 * can go from the shop to the founder's inbox without passing through us at all.
 *
 * What we need instead is a way to know WHOSE card just arrived. That is this
 * migration: we mint a short reference, show it to the buyer, and they type it
 * into the gift message. The email arrives carrying the reference; the founder
 * matches it to the waiting claim and approves.
 *
 * `code` becomes nullable rather than being dropped. Some buyers will paste one
 * anyway (a card bought somewhere that does not email, a screenshot they typed
 * out), and a column that can still hold it is better than a flow that refuses
 * a customer who is trying to pay. It is simply no longer required, and no
 * longer the thing we ask for.
 *
 * The reference is generated by the API, not typed, so it is unique by
 * construction — but the index makes that true rather than intended, and it is
 * what the founder's lookup reads.
 */

/* eslint-disable camelcase */

exports.shorthands = undefined;

exports.up = (pgm) => {
  pgm.sql(`
alter table gift_redemptions
  alter column code drop not null,
  add column reference text;

-- Backfill any row from the code-pasting era so the column can carry the
-- lookup for every row, old and new.
update gift_redemptions set reference = 'LEGACY-' || left(id::text, 8)
 where reference is null;

alter table gift_redemptions alter column reference set not null;

create unique index gift_redemptions_reference_uniq on gift_redemptions (reference);
  `);
};

exports.down = (pgm) => {
  pgm.sql(`
drop index if exists gift_redemptions_reference_uniq;
alter table gift_redemptions drop column if exists reference;
-- The code column is intentionally left nullable on the way down: rows created
-- by the reference flow have none, and restoring NOT NULL would fail on them.
  `);
};
