import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { config } from './config.js';

/**
 * Server view of the shared taxonomy model (generated by
 * tools/build_plus_index.mjs). Used to turn per-content highlight counts into
 * the dashboard tree and to resolve a topic key to its content_ids. The taxonomy
 * itself never lives in the DB; only the user's highlights do.
 */

interface Subtopic { key: string; fa: string; contentCount: number; contentIds: string[]; }
interface Cluster { key: string; fa: string; contentCount: number; contentIds: string[]; subtopics: Subtopic[]; }
interface ContentInfo { cluster: string; subtopic: string | null; type: string; title: string; url: string; secondary: string[]; }
interface IndexFile { version: number; clusters: Cluster[]; byContent: Record<string, ContentInfo>; }

let cached: IndexFile | null = null;

function defaultPath(): string {
  const here = dirname(fileURLToPath(import.meta.url)); // plus-api/src (or dist)
  return resolve(here, '..', '..', 'plus', 'content-index.json');
}

export function getIndex(): IndexFile {
  if (cached) return cached;
  const path = config.contentIndexPath || defaultPath();
  try {
    cached = JSON.parse(readFileSync(path, 'utf8')) as IndexFile;
  } catch (err) {
    // Missing index must not crash the API; the tree just comes back empty.
    // eslint-disable-next-line no-console
    console.warn(`[content-index] could not load ${path}; tree/topic will be empty`);
    cached = { version: 0, clusters: [], byContent: {} };
  }
  return cached;
}

/** Resolve a topic key to its content_ids and a Persian label. */
export function resolveTopic(topic: string): { fa: string; contentIds: string[] } | null {
  const idx = getIndex();
  let scope = topic;
  let kind = '';
  const colon = topic.indexOf(':');
  if (colon !== -1) { kind = topic.slice(0, colon); scope = topic.slice(colon + 1); }

  if (kind === 'type' || (!kind && false)) {
    const contentIds = Object.keys(idx.byContent).filter((id) => idx.byContent[id].type === scope);
    if (!contentIds.length) return null;
    return { fa: scope, contentIds };
  }

  // cluster (explicit or bare)
  if (kind === 'cluster' || !kind) {
    const c = idx.clusters.find((x) => x.key === scope);
    if (c) return { fa: c.fa, contentIds: c.contentIds };
  }
  // subtopic (explicit or bare fallback)
  if (kind === 'subtopic' || !kind) {
    for (const c of idx.clusters) {
      const s = c.subtopics.find((x) => x.key === scope);
      if (s) return { fa: s.fa, contentIds: s.contentIds };
    }
  }
  return null;
}

/** Turn a content_id -> count map into the dashboard tree (counts + links). */
export function buildTree(counts: Map<string, number>) {
  const idx = getIndex();
  const sum = (ids: string[]) => ids.reduce((acc, id) => acc + (counts.get(id) || 0), 0);
  return {
    clusters: idx.clusters.map((c) => ({
      key: c.key,
      fa: c.fa,
      topicKey: 'cluster:' + c.key,
      count: sum(c.contentIds),
      contentCount: c.contentCount,
      subtopics: c.subtopics.map((s) => ({
        key: s.key,
        fa: s.fa,
        topicKey: 'subtopic:' + s.key,
        count: sum(s.contentIds),
        contentCount: s.contentCount,
      })),
    })),
  };
}
