import { readFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { config } from './config.js';

/**
 * Server view of the shared taxonomy model (generated by
 * tools/build_plus_index.mjs). Used to turn per-content highlight counts into
 * the dashboard tree and to resolve a topic key to its content_ids. The taxonomy
 * itself never lives in the DB; only the user's highlights do.
 */

interface Subtopic { key: string; fa: string; contentCount: number; contentIds: string[]; }
interface Cluster { key: string; fa: string; contentCount: number; contentIds: string[]; subtopics: Subtopic[]; }
interface Folder { key: string; fa: string; url: string; total: number; }
interface ContentInfo { cluster: string | null; subtopic: string | null; type: string; title: string; url: string; secondary: string[]; }
interface IndexFile { version: number; folders: Folder[]; clusters: Cluster[]; byContent: Record<string, ContentInfo>; }

let cached: IndexFile | null = null;
let cachedMtimeMs = 0;

function defaultPath(): string {
  const here = dirname(fileURLToPath(import.meta.url)); // plus-api/src (or dist)
  return resolve(here, '..', '..', 'plus', 'content-index.json');
}

/**
 * Load the index, reloading automatically when the file changes on disk (so
 * newly published content is reflected without an API restart; the dashboard
 * checks for new content each time it opens).
 */
export function getIndex(): IndexFile {
  const path = config.contentIndexPath || defaultPath();
  try {
    const mtime = statSync(path).mtimeMs;
    if (cached && mtime === cachedMtimeMs) return cached;
    cached = JSON.parse(readFileSync(path, 'utf8')) as IndexFile;
    cachedMtimeMs = mtime;
  } catch (err) {
    if (cached) return cached; // keep the last good copy on a transient read error
    // eslint-disable-next-line no-console
    console.warn(`[content-index] could not load ${path}; tree/topic will be empty`);
    cached = { version: 0, folders: [], clusters: [], byContent: {} };
  }
  return cached;
}

export function getFolders(): Folder[] {
  return getIndex().folders || [];
}

/** The folder ("پادکست"، "نوت‌کست"، ...) a content_id belongs to. */
export function folderOf(contentId: string): string {
  return contentId.split('/')[0];
}

/** Resolve a topic key to its content_ids and a Persian label. */
export function resolveTopic(topic: string): { fa: string; contentIds: string[] } | null {
  const idx = getIndex();
  let scope = topic;
  let kind = '';
  const colon = topic.indexOf(':');
  if (colon !== -1) { kind = topic.slice(0, colon); scope = topic.slice(colon + 1); }

  // folder:<key> is resolved by the caller via a content_id prefix query (it must
  // include every highlight in the folder, even on pages not in the index).
  if (kind === 'type') {
    const contentIds = Object.keys(idx.byContent).filter((id) => idx.byContent[id].type === scope);
    if (!contentIds.length) return null;
    return { fa: scope, contentIds };
  }

  // cluster (explicit or bare)
  if (kind === 'cluster' || !kind) {
    const c = idx.clusters.find((x) => x.key === scope);
    if (c) return { fa: c.fa, contentIds: c.contentIds };
  }
  // subtopic (explicit or bare fallback)
  if (kind === 'subtopic' || !kind) {
    for (const c of idx.clusters) {
      const s = c.subtopics.find((x) => x.key === scope);
      if (s) return { fa: s.fa, contentIds: s.contentIds };
    }
  }
  return null;
}

/** Persian label for a folder key, or the key itself if unknown. */
export function folderLabel(key: string): string {
  return getFolders().find((f) => f.key === key)?.fa || key;
}

/**
 * The dashboard navigation tree: the real site folders, each with the user's
 * highlight count and its landing-page link (spec change: folder-based tree).
 * Counts are grouped by content_id prefix.
 */
export function buildFolderTree(counts: Map<string, number>) {
  const byFolder = new Map<string, number>();
  for (const [cid, n] of counts) {
    const f = folderOf(cid);
    byFolder.set(f, (byFolder.get(f) || 0) + n);
  }
  return getFolders().map((f) => ({
    key: f.key, fa: f.fa, url: f.url, total: f.total, count: byFolder.get(f.key) || 0,
  }));
}

/** Turn a content_id -> count map into the pillar tree (Phase 3 map reuses it). */
export function buildTree(counts: Map<string, number>) {
  const idx = getIndex();
  const sum = (ids: string[]) => ids.reduce((acc, id) => acc + (counts.get(id) || 0), 0);
  return {
    clusters: idx.clusters.map((c) => ({
      key: c.key,
      fa: c.fa,
      topicKey: 'cluster:' + c.key,
      count: sum(c.contentIds),
      contentCount: c.contentCount,
      subtopics: c.subtopics.map((s) => ({
        key: s.key,
        fa: s.fa,
        topicKey: 'subtopic:' + s.key,
        count: sum(s.contentIds),
        contentCount: s.contentCount,
      })),
    })),
  };
}
