import { readFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { config } from './config.js';

/**
 * Server view of the shared taxonomy model (generated by
 * tools/build_plus_index.mjs). Used to turn per-content highlight counts into
 * the dashboard tree and to resolve a topic key to its content_ids. The taxonomy
 * itself never lives in the DB; only the user's highlights do.
 */

interface Subtopic { key: string; fa: string; contentCount: number; contentIds: string[]; }
interface Cluster { key: string; fa: string; contentCount: number; contentIds: string[]; subtopics: Subtopic[]; }
interface Folder { key: string; fa: string; url: string; total: number; }
interface ContentInfo { cluster: string | null; subtopic: string | null; type: string; title: string; url: string; secondary: string[]; }
/** One real site #hashtag, with every content_id that carries it. */
export interface Tag { key: string; fa: string; contentCount: number; contentIds: string[]; }
interface IndexFile { version: number; folders: Folder[]; clusters: Cluster[]; tags: Tag[]; aliases?: Record<string, string>; byContent: Record<string, ContentInfo>; }

let cached: IndexFile | null = null;
let cachedMtimeMs = 0;
/** Set by content-refresh.ts once a published copy has been fetched and validated. */
let remote: IndexFile | null = null;

function defaultPath(): string {
  const here = dirname(fileURLToPath(import.meta.url)); // plus-api/src (or dist)
  return resolve(here, '..', '..', 'plus', 'content-index.json');
}

/**
 * Adopt a freshly published index fetched from the live site (content-refresh.ts).
 *
 * In production the on-disk copy is baked into the image, so the mtime reload
 * below never fires and every publish would otherwise need a rebuild. This is
 * the way in — and it is deliberately hard to walk through. The payload must
 * parse, carry all four collections, and describe at least one content item;
 * anything else (an HTML error page from a CDN, a half-written file, a
 * successful request for the wrong URL) is refused and the current copy stands.
 *
 * The empty-index check is the important one: a valid-but-empty file would be
 * accepted by every structural test and would silently blank the dashboard tree
 * and the assistant's whole catalog. A publish never empties this file, so an
 * empty one means something upstream broke, and "keep yesterday's taxonomy" is
 * always the better answer than "serve nothing".
 *
 * @returns true if the payload was adopted.
 */
export function applyRemoteIndex(raw: unknown): boolean {
  const idx = raw as IndexFile | null;
  if (!idx || typeof idx !== 'object') return false;
  if (!Array.isArray(idx.folders) || !Array.isArray(idx.clusters) || !Array.isArray(idx.tags)) return false;
  if (!idx.byContent || typeof idx.byContent !== 'object' || Array.isArray(idx.byContent)) return false;
  if (Object.keys(idx.byContent).length === 0) return false;
  remote = idx;
  return true;
}

/** Which copy is being served — for the boot/refresh log and for tests. */
export function indexSource(): string {
  return remote ? `published (version ${remote.version ?? 0})` : 'image/disk';
}

/** Test-only: forget the fetched copy so a case can start from the baked file. */
export function resetRemoteIndex(): void {
  remote = null;
}

/**
 * Load the index. A published copy fetched at runtime wins; otherwise the file
 * on disk is used, reloaded automatically when its mtime changes (which is what
 * happens in local development, where the file is the repo's own).
 */
export function getIndex(): IndexFile {
  if (remote) return remote;
  const path = config.contentIndexPath || defaultPath();
  try {
    const mtime = statSync(path).mtimeMs;
    if (cached && mtime === cachedMtimeMs) return cached;
    cached = JSON.parse(readFileSync(path, 'utf8')) as IndexFile;
    cachedMtimeMs = mtime;
  } catch (err) {
    if (cached) return cached; // keep the last good copy on a transient read error
    // eslint-disable-next-line no-console
    console.warn(`[content-index] could not load ${path}; tree/topic will be empty`);
    cached = { version: 0, folders: [], clusters: [], tags: [], aliases: {}, byContent: {} };
  }
  return cached;
}

export function getFolders(): Folder[] {
  return getIndex().folders || [];
}

/** Raw clusters (with contentIds/subtopics) — the taxonomy a recommender walks. */
export function getClusters(): Cluster[] {
  return getIndex().clusters || [];
}

/** Every real site #hashtag, each with its own content_ids — the case-assistant's keyword-search catalog. */
export function getTags(): Tag[] {
  return getIndex().tags || [];
}

/**
 * Orthographic variants of one word (بایومیمتیک -> بیومیمتیک), authored in
 * dentcast-hashtag-reference.json. case-assistant.ts folds these into both the
 * tag and the query before tokenizing, so a concept stays reachable through
 * every spelling without carrying every spelling on every article.
 */
export function getAliases(): Record<string, string> {
  return getIndex().aliases || {};
}

/** Title/url/type for a content_id (pathway steps resolve display metadata through this), or null if unknown. */
export function getContentInfo(contentId: string): ContentInfo | null {
  return getIndex().byContent[contentId] || null;
}

/** The folder ("پادکست"، "نوت‌کست"، ...) a content_id belongs to. */
export function folderOf(contentId: string): string {
  return contentId.split('/')[0];
}

/** Resolve a topic key to its content_ids and a Persian label. */
export function resolveTopic(topic: string): { fa: string; contentIds: string[] } | null {
  const idx = getIndex();
  let scope = topic;
  let kind = '';
  const colon = topic.indexOf(':');
  if (colon !== -1) { kind = topic.slice(0, colon); scope = topic.slice(colon + 1); }

  // folder:<key> is resolved by the caller via a content_id prefix query (it must
  // include every highlight in the folder, even on pages not in the index).
  if (kind === 'type') {
    const contentIds = Object.keys(idx.byContent).filter((id) => idx.byContent[id].type === scope);
    if (!contentIds.length) return null;
    return { fa: scope, contentIds };
  }

  // cluster (explicit or bare)
  if (kind === 'cluster' || !kind) {
    const c = idx.clusters.find((x) => x.key === scope);
    if (c) return { fa: c.fa, contentIds: c.contentIds };
  }
  // subtopic (explicit or bare fallback)
  if (kind === 'subtopic' || !kind) {
    for (const c of idx.clusters) {
      const s = c.subtopics.find((x) => x.key === scope);
      if (s) return { fa: s.fa, contentIds: s.contentIds };
    }
  }
  return null;
}

/** Persian label for a folder key, or the key itself if unknown. */
export function folderLabel(key: string): string {
  return getFolders().find((f) => f.key === key)?.fa || key;
}

/**
 * The dashboard navigation tree: the real site folders, each with the user's
 * highlight count and its landing-page link (spec change: folder-based tree).
 * Counts are grouped by content_id prefix.
 */
export function buildFolderTree(counts: Map<string, number>) {
  const byFolder = new Map<string, number>();
  for (const [cid, n] of counts) {
    const f = folderOf(cid);
    byFolder.set(f, (byFolder.get(f) || 0) + n);
  }
  return getFolders().map((f) => ({
    key: f.key, fa: f.fa, url: f.url, total: f.total, count: byFolder.get(f.key) || 0,
  }));
}

/** Turn a content_id -> count map into the pillar tree (Phase 3 map reuses it). */
export function buildTree(counts: Map<string, number>) {
  const idx = getIndex();
  const sum = (ids: string[]) => ids.reduce((acc, id) => acc + (counts.get(id) || 0), 0);
  return {
    clusters: idx.clusters.map((c) => ({
      key: c.key,
      fa: c.fa,
      topicKey: 'cluster:' + c.key,
      count: sum(c.contentIds),
      contentCount: c.contentCount,
      subtopics: c.subtopics.map((s) => ({
        key: s.key,
        fa: s.fa,
        topicKey: 'subtopic:' + s.key,
        count: sum(s.contentIds),
        contentCount: s.contentCount,
      })),
    })),
  };
}
