// The premium view of the topical index — /pillar/ and /pillar/<slug>/.
//
// The page a crawler (and everyone else) receives is the flat one: on the hub,
// ten pillars with their totals; on a pillar page, every article in one list,
// newest first. That HTML is the indexed surface and never changes.
//
// What premium buys is the ARRANGEMENT — the same links, foldered into
// subtopics and ordered along each pillar's own reading chain. That
// arrangement is not in the page. It ships beside it in structure.json and is
// layered in here, only after /me confirms a subscription. Keeping it out of
// the HTML is the whole point: two orderings of the same 112 links in one
// document is a duplicate-content problem for us and a worse page for the
// reader who is not paying for the second one.
//
// Three rules the rest of this file follows:
//
//   1. Never blank the page waiting for an answer. The flat list stays exactly
//      as served until structure.json is in hand and parsed. A slow or dead
//      API means the reader keeps the page they already had — not a spinner,
//      not an empty frame.
//   2. `meStatus() === 'error'` is NOT 'not premium'. Same distinction spot.js
//      draws: "we could not ask" must never render as a downgrade to someone
//      who paid. On an error we leave the page alone and try again on the
//      next navigation.
//   3. The reader's choice outranks the default. Someone who switches back to
//      the date list stays there on the next pillar page too, until they say
//      otherwise — the arrangement is a feature, not an obligation.
import { currentUser, meStatus } from '../plus/js/api.js';

const VIEW_KEY = 'dc:pillar-view';       // 'chain' (default) | 'flat'
const ASSET_V = new URL(import.meta.url).search;   // carry ?v= onto the fetch

const isHub = /^\/pillar\/?$/.test(location.pathname)
  || /^\/pillar\/index\.html$/.test(location.pathname);

function lsGet(k) { try { return localStorage.getItem(k) || ''; } catch (_) { return ''; } }
function lsSet(k, v) { try { localStorage.setItem(k, v); } catch (_) { /* private mode */ } }

async function structure() {
  const base = isHub ? '/pillar/structure.json' : location.pathname.replace(/\/?$/, '/') + 'structure.json';
  const res = await fetch(base + ASSET_V, { credentials: 'omit' });
  if (!res.ok) throw new Error('structure ' + res.status);
  return res.json();
}

// ── hub: put each pillar's subtopic breakdown back on its card ──────────────
function fillHub(data) {
  document.querySelectorAll('.pillar-card-row').forEach((row) => {
    const info = data.pillars && data.pillars[row.dataset.pillar];
    const ul = row.querySelector('.pillar-card-subtopics');
    if (!info || !ul) return;
    ul.innerHTML = info.subtopics.map((s) => (
      '<li><span class="subtopic-label"></span><span class="subtopic-chip"></span></li>'
    )).join('');
    // Text set as text, not markup: these strings come from a fetched file, and
    // innerHTML for them would be an injection path for anyone who can serve it.
    ul.querySelectorAll('li').forEach((li, i) => {
      li.querySelector('.subtopic-label').textContent = info.subtopics[i].title_fa;
      li.querySelector('.subtopic-chip').textContent = faDigits(info.subtopics[i].count);
    });
    ul.hidden = false;
  });

  // Nothing left to sell this reader. The hub has no second view to offer, so
  // the banner just goes — unlike the pillar page, where its row becomes the
  // view switch.
  const banner = document.querySelector('[data-premium-banner]');
  if (banner) banner.remove();

  const stats = document.querySelector('[data-index-stats]');
  if (stats && data.total_subtopics && !stats.querySelector('[data-subtopic-chip]')) {
    const chip = document.createElement('span');
    chip.className = 'pillar-index-stat-chip';
    chip.setAttribute('data-subtopic-chip', '');
    const v = document.createElement('span');
    v.className = 'stat-value';
    v.textContent = faDigits(data.total_subtopics);
    const l = document.createElement('span');
    l.className = 'stat-label';
    l.textContent = 'زیرموضوع';
    chip.append(v, l);
    stats.appendChild(chip);
  }
}

function faDigits(n) {
  return String(n).replace(/\d/g, (d) => '۰۱۲۳۴۵۶۷۸۹'[+d]);
}

// ── pillar page: swap the flat list for the foldered one ───────────────────
//
// cards_html is generated by tools/build_pillar.py from the same brain entries
// that produced the flat list already in this document — it is our own build
// output served from our own origin, the identical markup this page used to
// ship inline, which is why it goes in as markup rather than being rebuilt
// node by node here. Rebuilding it in JS would mean two renderers for one
// design, drifting apart on the first change to a card.
function fillPillar(data) {
  const flat = document.querySelector('[data-flat-list]');
  const head = document.querySelector('.pillar-flat-head');
  const note = document.querySelector('.pillar-flat-note');
  if (!flat || !data.cards_html) return;

  const chain = document.createElement('section');
  chain.className = 'pillar-cards';
  chain.setAttribute('data-chain-list', '');
  chain.setAttribute('aria-label', 'دسته‌بندی موضوعی');
  chain.innerHTML = data.cards_html;
  flat.parentNode.insertBefore(chain, flat);

  const show = (mode) => {
    const asChain = mode === 'chain';
    chain.hidden = !asChain;
    flat.hidden = asChain;
    if (head) head.hidden = asChain;
    if (note) note.hidden = asChain;
    lsSet(VIEW_KEY, mode);
    state(mode);
  };

  // The banner is gone for this reader — nothing left to sell them — but the
  // row keeps its place so the page does not jump when the swap lands.
  const banner = document.querySelector('[data-premium-banner]');
  let bar = null;
  function state(mode) {
    if (!bar) {
      bar = document.createElement('div');
      bar.className = 'pillar-premium-state';
      if (banner) banner.replaceWith(bar);
      else flat.parentNode.insertBefore(bar, chain);
    }
    bar.textContent = '';
    const b = document.createElement('b');
    b.textContent = 'نمای پریمیوم';
    const what = document.createElement('span');
    what.textContent = mode === 'chain'
      ? 'زیرموضوع‌بندی‌شده، به ترتیب خواندن'
      : 'همهٔ مطالب، به‌ترتیب تاریخ';
    const spacer = document.createElement('span');
    spacer.className = 'spacer';
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.textContent = mode === 'chain' ? 'نمای زمانی' : 'نمای زیرموضوعی';
    btn.addEventListener('click', () => show(mode === 'chain' ? 'flat' : 'chain'));
    bar.append(b, what, spacer, btn);
  }

  show(lsGet(VIEW_KEY) === 'flat' ? 'flat' : 'chain');
}

(async function main() {
  let user;
  try {
    user = await currentUser();
  } catch (_) {
    return;
  }
  // 'error' means the question never got asked. Leaving the page untouched is
  // the safe direction: a premium reader sees the flat list for one navigation
  // instead of a paid feature being declared absent.
  if (meStatus() === 'error') return;
  if (!user || user.tier !== 'premium') return;

  let data;
  try {
    data = await structure();
  } catch (_) {
    return;
  }
  if (!data || data.version !== 1) return;
  if (isHub) fillHub(data);
  else fillPillar(data);
})();
