import { chromium } from 'playwright';
const SITE = 'http://localhost:5500', API = 'http://localhost:8787';
const r = await fetch(`${API}/auth/otp/request`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ phone: '09120000001' }) });
const v = await fetch(`${API}/auth/otp/verify`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ phone: '09120000001', code: (await r.json()).dev_code }) });
const cookie = v.headers.get('set-cookie').split(';')[0].split('=').slice(1).join('=');
const b = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await b.newContext({ viewport: { width: 1200, height: 860 } });
await ctx.addCookies([{ name: 'dcp_session', value: cookie, domain: 'localhost', path: '/', httpOnly: true, sameSite: 'Lax' }]);
const p = await ctx.newPage();
await p.goto(SITE + '/chairside/chairside-25.html', { waitUntil: 'networkidle' });
await p.waitForTimeout(700);
await p.click('.dcp-person-btn.is-user'); await p.waitForTimeout(200);
await p.click('.dcp-person-menu .dcp-person-item:nth-child(1)'); await p.waitForTimeout(800);
await p.screenshot({ path: 'scripts-dev/overlay-dashboard.png' });
await p.click('.dcp-person-btn.is-user'); await p.waitForTimeout(300);
await p.click('.dcp-person-btn.is-user'); await p.waitForTimeout(200);
await p.click('.dcp-person-menu .dcp-person-item:nth-child(2)'); await p.waitForTimeout(800);
await p.screenshot({ path: 'scripts-dev/overlay-profile.png' });
console.log('shots saved');
await b.close();
